const {chromium}=require('C:/Users/kuzme/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1280,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('file:///D:/projects/cubechat/design-previews/matcha-motion-v2/index.html');
await page.locator('.card').last().scrollIntoViewIfNeeded();await page.locator('header').scrollIntoViewIfNeeded();
await page.waitForFunction(()=>Array.from(document.querySelectorAll('main img')).every(im=>im.complete&&im.naturalWidth>0));
if(await page.locator('.card').count()!==24)throw Error('Missing cards');
await page.locator('#pause').click();
if(await page.locator('#pause').innerText()!=='Воспроизвести')throw Error('Pause failed');
await page.locator('#theme').click();
if(!await page.locator('body').evaluate(e=>e.classList.contains('dark')))throw Error('Theme failed');
await page.locator('[data-open="cat-wave"]').click();
if(!await page.locator('#detail').evaluate(e=>e.open))throw Error('Detail failed');
if(!((await page.locator('#get-webp').getAttribute('href')).endsWith('cat-wave.webp')))throw Error('Download target');
await page.locator('.close').click();await page.locator('#theme').click();
await page.screenshot({path:'D:/projects/cubechat/design-previews/matcha-motion-v2/preview-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'D:/projects/cubechat/design-previews/matcha-motion-v2/preview-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
if(errors.length)throw Error(errors.join('; '));console.log(JSON.stringify({cards:24,pause:true,theme:true,detail:true,mobileOverflow:false,errors}));
await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
