from pathlib import Path
r=Path('D:/projects/cubechat/design-previews/motion-quality')
styles='''*{box-sizing:border-box}body{margin:0;background:#f4f3ea;color:#30382a;font:16px/1.5 system-ui,sans-serif}body.dark{background:#20251f;color:#edf0e3}main{max-width:1050px;margin:auto;padding:36px 24px 60px}h1{font-size:36px;margin:8px 0;letter-spacing:-.04em}h2{font-size:21px;margin:24px 0 10px}p{color:#7c866d}.tag{font-size:12px;letter-spacing:.1em}.controls{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}button,a{font:inherit;color:inherit;border:1px solid #9da68c;border-radius:24px;background:transparent;padding:9px 16px;text-decoration:none;cursor:pointer}.pair{display:grid;grid-template-columns:1fr 1fr;gap:16px}.card{padding:18px;text-align:center;border:1px solid #9da68c44;border-radius:22px;background:#ffffff28}.card img{display:block;width:100%;max-width:300px;margin:auto}.card span{display:block;font-size:13px;margin-top:10px;color:#849074}.small{margin:18px 0;display:flex;gap:14px;align-items:center}.small img{width:64px;height:64px}.note{font-size:13px;max-width:800px}@media(max-width:550px){main{padding:22px 14px}.pair{gap:8px}.card{padding:8px}h1{font-size:30px}}'''
html='<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Проверка движения — в работе</title><style>'+styles+'</style><main><div class="tag">CUBECHAT · РАБОЧАЯ ПРОВЕРКА</div><h1>Постоянная форма, живые жесты</h1><p>Четыре пробных движения из присланного видео. Исправление полного набора из 72 анимаций продолжается.</p><div class="controls"><button id="pause">Пауза</button><button id="theme">Тёмный фон</button><a href="../index.html">Все макеты</a></div>'
for stem,label in [('cat-morning','Потягивание'),('cat-laugh','Смех'),('cat-flower','Цветок'),('cat-victory','Кубок')]:
 html+='<h2>'+label+'</h2><div class="pair"><div class="card"><img data-base="../matcha-motion-v6/'+stem+'" src="../matcha-motion-v6/'+stem+'.webp" alt="Предыдущая анимация"><span>Предыдущая версия</span></div><div class="card"><img data-base="'+stem+'-rig" src="'+stem+'-rig.webp" alt="Пробная анимация отдельными частями"><span>Новая сборка · в работе</span></div></div>'
html+='<h2>В размере сообщения</h2><div class="small">'
for stem in ['cat-morning','cat-laugh','cat-flower','cat-victory']:html+='<img data-base="'+stem+'-rig" src="'+stem+'-rig.webp" alt="Пробный стикер">'
html+='</div><p class="note">Проверяем устойчивость контура, стыки деталей, мимику и привязку лап к предметам. Это рабочие образцы, а не готовая замена всей коллекции. Внешний вид и остальные действия ещё проходят доводку.</p></main><script>let paused=false;document.getElementById("pause").onclick=e=>{paused=!paused;document.querySelectorAll("img[data-base]").forEach(im=>im.src=im.dataset.base+(paused?".png":".webp"));e.currentTarget.textContent=paused?"Продолжить":"Пауза"};document.getElementById("theme").onclick=e=>{const on=document.body.classList.toggle("dark");e.currentTarget.textContent=on?"Светлый фон":"Тёмный фон"}</script></html>'
(r/'index.html').write_text(html,encoding='utf-8')
root=r.parent/'index.html';text=root.read_text(encoding='utf-8')
if 'motion-quality/index.html' not in text:text=text.replace('<div class="links">','<div class="links"><a href="motion-quality/index.html">Исправление движения · в работе</a>',1)
root.write_text(text,encoding='utf-8')
print('Working comparison page saved')
