const fs=require('fs');
const {chromium}=require('C:/Users/kuzme/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
 const root='D:/projects/cubechat/design-previews/matcha-motion-v6/';
 const endpoint=JSON.parse(fs.readFileSync(root+'preview-server.json','utf8')).url;
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1280,height:1000}});const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(endpoint);await page.locator('.card').last().scrollIntoViewIfNeeded();await page.locator('header').scrollIntoViewIfNeeded();
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('main img')).every(im=>im.complete&&im.naturalWidth>0));
 if(await page.locator('.card').count()!==72)throw Error('Card count');
 await page.locator('#pause').click();if(await page.locator('#pause').innerText()!=='Воспроизвести')throw Error('Pause');
 await page.locator('#theme').click();if(!await page.locator('body').evaluate(e=>e.classList.contains('dark')))throw Error('Theme');
 await page.locator('[data-open="cat-peek"]').click();await page.locator('#show-hd').click();
 await page.waitForFunction(()=>document.getElementById('zoom-hd').readyState>=2);
 const video=await page.locator('#zoom-hd').evaluate(v=>{const c=document.createElement('canvas');c.width=20;c.height=20;const x=c.getContext('2d');x.drawImage(v,0,0,20,20);return {width:v.videoWidth,height:v.videoHeight,duration:v.duration,alpha:x.getImageData(0,0,1,1).data[3],paused:v.paused}});
 if(video.width!==2048||video.height!==2048||video.alpha!==0||Math.abs(video.duration-6)>.1)throw Error(JSON.stringify(video));
 if(!(await page.locator('#get-png-2k').getAttribute('href')).endsWith('cat-peek.png'))throw Error('Download');
 await page.screenshot({path:root+'preview-detail.png'});await page.locator('.close').click();await page.locator('#theme').click();await page.locator('#pause').click();
 await page.locator('header').scrollIntoViewIfNeeded();await page.screenshot({path:root+'preview-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:root+'preview-mobile.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
 await page.goto(endpoint+'compare.html');await page.locator('figure').last().scrollIntoViewIfNeeded();
 await page.waitForFunction(()=>Array.from(document.images).every(im=>im.complete&&im.naturalWidth>0));
 if(await page.locator('figure').count()!==12)throw Error('Comparison count');
 await page.setViewportSize({width:1100,height:1000});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:root+'preview-comparison.png',fullPage:true});
 if(errors.length)throw Error(errors.join('; '));
 const result={cards:72,pause:true,theme:true,detail:true,video,comparisonPairs:6,mobileOverflow:false,errors};fs.writeFileSync(root+'validation-browser.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
