from pathlib import Path
p=Path('D:/projects/cubechat/design-previews/matcha-motion-v6/package.py')
s=p.read_text(encoding='utf-8-sig')
s=s.replace("for name in ['README.md','manifest.json','prompts.json','validation-preview.json','validation-2k.json','index.html']:out.write(root/name,name)","""for name in ['README.md','manifest.json','prompts.json','validation-preview.json','validation-2k.json']:out.write(root/name,name)
 html=(root/'index.html').read_text(encoding='utf-8').replace('<a class=\"pill\" href=\"compare.html\">Сравнить движения</a>','').replace('<a class=\"pill\" href=\"../matcha-motion/index.html\">Самые первые 8</a>','')
 out.writestr('index.html',html)""")
p.write_text(s,encoding='utf-8')
root=p.parent
rows={'cat-1':['thanks: bring paws together, bow, return','thinking: paw to chin, gaze up, opposite tilt','facepalm: raise paw, cover forehead, withdraw','hug: open arms, reach inward, release','tired: lower eyelids, rest head, reopen','waiting: look left and right, lift hourglass'], 'cat-2':['victory: lift trophy and smile, lower','sorry: paws together, eyes-closed bow, look up','morning: raise arms, yawn stretch, release','cozy: tuck blanket, snuggle, look up','flower: raise flower to nose, smell, lower','cookie: raise cookie, bite, chew, lower'], 'cat-3':['work: alternate keyboard paw presses, blink','hurry: running gait phases','birthday: pucker, blow candle, happy smile','nope: crossed arms, turn head both ways','music: hold earcups, tilt head left/right, open eyes','gaming: alternating thumb presses, grin'], 'cat-4':['rain: look up under umbrella, blink, forward','peek: sink into box, rise, paws on edge, sink','secret: lift finger to mouth, wink, lower','support: alternate raising pompoms, smile','recover: gentle head dip and blink, smile','popcorn: take a piece, carry to mouth, chew, lower'], 'emoji-1':['wink: eye open, half closed, wink, reopen','smirk: sideways glance, eyebrow lift, settle','eyeroll: pupil movement across upper eye','sleepy: mouth opens into yawn, closes','thinking: finger on chin, glance up, brow lift','giggle: hand covers mouth, eyes squeeze, release'], 'emoji-2':['cool: lower sunglasses, glance over them, raise','thanks: palms apart, meet, bow, straighten','grin: widen smile and lift cheeks, relax','rofl: small alternating tilts with laughter','tongue: wink, extend tongue, retract','relieved: close eyes, exhale, settle smile'], 'emoji-3':['skeptical: raise one eyebrow, narrow eye, relax','unamused: sideways gaze, blink','pleading: lower eyelids, close and reopen','starry: star eyes rotate and pulse, mouth opens','zipper: zipper pull tilts, eyes blink','shush: finger lifts to lips, blink, lower'], 'emoji-4':['hugging: hands move inward and open again','salute: lift hand to brow, blink, lower','sweat: sweat drops down original side','mindblown: cloud rises expands and settles','sobbing: tear streams lengthen and shorten','angel: halo tilts, eyelids close and reopen']}
import json
prompts=json.loads((root/'prompts.json').read_text(encoding='utf-8'))
prompts['motion_prompts_by_sheet']=rows
prompts['shared_prompt']='Use the existing six stickers in the supplied reference without redesign: preserve character, palette, proportions, markings, rendering and props. Four equal columns x six equal rows; four successive motion poses per row, same scale, anchor and ground line. No text or gridlines. Uniform magenta background for keying (first sheet requested alpha and returned checkerboard; cleaned at assembly). Only action poses and facial expressions change.'
(root/'prompts.json').write_text(json.dumps(prompts,ensure_ascii=False,indent=2),encoding='utf-8')
print('Standalone archive links and motion prompt records prepared')
