const fs=require('fs');const {chromium}=require('C:/Users/kuzme/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const root='D:/projects/cubechat/design-previews/matcha-motion-v4/';const endpoint=JSON.parse(fs.readFileSync(root+'preview-server.json','utf8')).url;const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1280,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(endpoint);await page.locator('.card').last().scrollIntoViewIfNeeded();await page.locator('header').scrollIntoViewIfNeeded();await page.waitForFunction(()=>Array.from(document.querySelectorAll('main img')).every(im=>im.complete&&im.naturalWidth>0));if(await page.locator('.card').count()!==56)throw Error('Card count');
await page.locator('#filter-new').click();if(await page.locator('.card:visible').count()!==16)throw Error('New filter');await page.locator('#filter-new').click();if(await page.locator('.card:visible').count()!==56)throw Error('All filter');await page.locator('#pause').click();if(await page.locator('#pause').innerText()!=='Воспроизвести')throw Error('Pause');
await page.locator('#theme').click();if(!await page.locator('body').evaluate(e=>e.classList.contains('dark')))throw Error('Theme');
await page.locator('[data-open="cat-morning"]').click();await page.locator('#show-hd').click();await page.waitForFunction(()=>document.getElementById('zoom-hd').readyState>=2);
const video=await page.locator('#zoom-hd').evaluate(v=>{const c=document.createElement('canvas');c.width=10;c.height=10;const ctx=c.getContext('2d');ctx.drawImage(v,0,0,10,10);return {width:v.videoWidth,height:v.videoHeight,alpha:ctx.getImageData(0,0,1,1).data[3],paused:v.paused}});
if(video.width!==2048||video.height!==2048||video.alpha!==0)throw Error('2K video dimensions/transparency: '+JSON.stringify(video));
if(!(await page.locator('#get-png-2k').getAttribute('href')).endsWith('cat-morning.png'))throw Error('2K download');
await page.screenshot({path:root+'preview-2k-detail.png'});await page.locator('.close').click();await page.locator('#theme').click();await page.locator('header').scrollIntoViewIfNeeded();await page.screenshot({path:root+'preview-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:root+'preview-mobile.png',fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');if(errors.length)throw Error(errors.join('; '));console.log(JSON.stringify({cards:56,pause:true,theme:true,detail:true,video,mobileOverflow:false,errors}));await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
